services:
  cost_analysis:
    deploy:
      resources:
        limits:
          memory: 512M # Hard limit: Container cannot exceed 512MB
        reservations:
          memory: 256M # Guaranteed reservation: Container is guaranteed at least 256MB
    build:
      context: .
    container_name: cost_analysis
    ports:
      - "9003:5000"
    volumes:
      - ./saves:/app/saves
      - ./working:/app/working
    restart: unless-stopped
